version: '3.8'

services:
  app:
    image: 'sha256:190c9260b03c35967bf4eb953b51109dcfbc02539c7380e29b43813e94616153'
    container_name: appl
    expose:
      - '8080'
    ports:
      - '8181:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=dbl  # подставляется в переменную "DB_URL" jdbc:postgresql://${DB_URL:localhost}:5432/bank в application.yml
      - DATABASE_HOST=org.postgresql.Driver
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: dbl
    expose:
      - '5432'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres