version: '3.8'

services:
  app:
    image: 'sha256:3e4fd178b8895ca57651bbd7b012462403e0e0a26ef25aeec7f9b193fa6e6f10'
    container_name: appl
    expose:
      - '8080'
    ports:
      - '8181:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=dbl
      - DATABASE_HOST=org.postgresql.Driver
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: dbl
    expose:
      - '5432'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres