spring:
  application:
    name: dock_demo

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/bank  # DB_URL тянем из docker-compose.yml (localhost по умолчанию)

    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

